[project]
name = "rgbt-traffic-data-fusion"
version = "0.1.0"
description = ""
authors = [
    {name = "Lucas Ikuhara",email = "ikuhara@ibm.com"}
]
readme = "README.md"
requires-python = ">=3.12"



[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
ultralytics = "^8.4.117"
huggingface-hub = "^1.27.0"
pycocotools = "^2.0.11"
scikit-image = "^0.26.0"
scikit-learn = "^1.9.0"
ensemble-boxes = "^1.0.9"
