[experiments.rgb]
name = "rbg-yolo-v8-s"
dataset_base_dir = "aau-rainsnow"
dataset_file = "aau-rainsnow/aauRainSnow-rgb.json"
model_name = "rbg_yolo_v8_x"
output_path = "rgb_predictions.json"

[experiments.thermal]
name = "thermal-yolo-v8-x"
dataset_base_dir = "aau-rainsnow"
dataset_file = "aau-rainsnow/aauRainSnow-thermal.json"
model_name = "thermal_yolo_v8_s"
output_path = "thermal_predictions.json"

[training]
work_dir           = "runs/kfold"
input_model_rgb     = "yolov8x.pt"
output_model_rgb    = "rgb_yolo_finetuned.pt"
input_model_thermal = "yolov8x.pt"
output_model_thermal = "thermal_yolo_finetuned.pt"
n_splits      = 5
epochs        = 10
imgsz         = 640
batch         = 8
freeze        = 10   # 21 = detection head only; 10 aggregation + det
